---
title: "FCST"
output: 
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: mesoda_ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.path = "../figures/",
  fig.retina = TRUE,
  # fig.height = 3,
  dev = "png",
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  dpi = 300
)
library(mesoda)
library(metR)
library(tidyverse)
library(lubridate)
library(data.table)
library(here)
library(patchwork)
library(unglue)
library(knitr)
library(kableExtra)

map_arg <- rnaturalearth::ne_states(country = c("argentina"), 
                                    returnclass = "sf")
map_limitrofes <- rnaturalearth::ne_countries(country = c("Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")

square <- fread(here("analysis", "data", "derived_data", "dominio_square.csv"))
square2 <- fread(here("analysis", "data", "derived_data", "dominio_square2.csv"))
coord <- fread(here("analysis", "data", "derived_data", "coordenadas.csv"))


geom_mapa <- function(fill = NA) {
  list(geom_sf(data = map_arg, fill = fill, color = "black", size = 0.1, inherit.aes = FALSE),
       geom_sf(data = map_limitrofes, fill = fill, color = "black", size = 0.1, inherit.aes = FALSE),
       coord_sf(ylim = c(-42, -19), xlim = c(-76, -51)),
       scale_x_longitude(ticks = 5),
       scale_y_latitude(ticks = 5))
}

arg_topo <- metR::GetTopography(-75+360, -50+360, -20, -60, resolution = 1/10)
arg_topo[, lon := metR::ConvertLongitude(lon)]

cordillera <- list(
  ggnewscale::new_scale_fill(),
  geom_contour_fill(data = arg_topo, aes(x = lon, y = lat, 
                                         z = h),
                    breaks = seq(1500, 8000, by = 700)),
  scale_fill_gradient(low = "#E2E6E6", high = "#7E7E7E", guide = "none",
                      oob = scales::squish))

scale_date <- function(ini = 20181120180000, end = 20181123120000,
                       break_bin = "6 hour") {
  scale_x_datetime(breaks = seq.POSIXt(ymd_hms(ini), ymd_hms(end), by = break_bin),
                   labels = function(x) {
                     fifelse(hour(x) == 0, format(x, "%H\n%b %d"), format(x, "%H"))
                   }) 
}

obs.type <- tribble(
  ~type, ~code,
  120, "ADPUPA",
  130, "AIRCFT-AIREP",
  131, "AIRCFT-AMDAR",
  133, "AIRCAR",
  180, "SFCSHP",
  181, "ADPSFC",
  187, "ADPSFC\nno pressure",
  220, "ADPUPA",
  221, "ADPUPA-PIBAL",
  230, "AIRCFT-AIREP",
  231, "AIRCFT-AMDAR",
  233, "AIRCAR",
  280, "SFCSHP",
  281, "ADPSFC",
  287, "ADPSFC\nno pressure",
  290, "ASCATW"
) %>% 
  setDT()

fisica <- data.table(mem = as.character(formatC(1:60, flag = "0", width = 3)),
                     fisica = rep(c("KF-YSU", 
                                    "BMJ-YSU",
                                    "GF-YSU",
                                    "KF-MYJ",
                                    "BMJ-MYJ",
                                    "GF-MYJ",
                                    "KF-MYNN2",
                                    "BMJ-MYNN2",
                                    "GF-MYNN2"), length.out = 60)) %>% setDT()

multiespectrales <- c("airs_aqua",
                      "iasi_metop-a",
                      "iasi_metop-b")

experiments <- c("E4", "E5", "E6", "E7")
#Color blind friendly but E4 y E7 parecidos en Desaturated
colores_exp <- c(E4 = "#0077BB", E5 = "#88CCEE", E6 = "#EE7733", E7 = "#CC3311") 
# colores_exp <- c(E4 = "#225555", E5 = "#CCBB44", E6 = "#CC6677", E7 = "#882255")
satinfo <- fread(here("analysis", "data", "derived_data", "satinfo.txt")) %>% 
  setnames(c("!sensor/instr/sat", "chan"), c("sensor", "channel"))
derived_data <- "/home/paola.corrales/datosmunin/EXP/derived_data/"

```


### FSS

Acumulados a 6 hs

```{r}
files <- Sys.glob("/home/paola.corrales/mesoda/analysis/data/derived_data/fss_6h_fcst_ens_*_E[4-7]_ens.csv")

fss <- purrr::map(files, function(f) {
  
  meta <- unglue(basename(f), "fss_6h_fcst_ens_{ini_date}_{exp}_ens.csv")
  
  fread(f) %>% 
    .[, date := as_datetime(date)] %>% 
    .[, ini_date := ymd_h(meta[[1]][["ini_date"]])]
}) %>% 
  rbindlist()

fss %>% 
  ggplot(aes(date, fss)) +
  geom_hline(yintercept = 1, color = "darkgray") +
  geom_line(aes(color = exp, linetype = factor(ini_date))) +
  # geom_point(aes(color = exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date(20181122000000, 20181123000000, "12 hours") +
  facet_grid(w~q, labeller = labeller(q = c("1" = "1 mm", "5" = "5 mm", 
                                            "10" = "10 mm", "25" = "25 mm"),
                                      w = c("1" = "1 km", "5" = "50 km", 
                                            "11" = "100 km", 
                                            "51" = "500 km", "101" = "1000 km"))) +
  labs(color = NULL, x = NULL, linetype = NULL) +
  theme_minimal()

```




### Soundings

```{r message=FALSE, warning=FALSE}
files <- Sys.glob("/home/paola.corrales/datosmunin/EXP/E*/FCST/*/sondeos/*")
files <- files[str_detect(files, "_01_")]

sondeos <- purrr::map(files, function(f){
  
  fread(f) %>% 
    .[, value := fifelse(variable %in% c("t", "td"), value + 273.15, value)] %>% 
    .[, launch_time := as_datetime(launch_time)] %>% 
    .[, fcst_exp := basename(dirname(dirname(f)))]
  
}) %>% 
  rbindlist()

miembros <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/sondeos_agregados.rds") %>% 
  .[, mem := formatC(mem, width = 3, flag = "0")] %>% 
  fisica[., on = "mem"] %>% 
  separate(fisica, into = c("cumulus", "pbl"))



media <- read_rds("/home/paola.corrales/datosmunin/EXP/derived_data/sondeos_media.rds") %>% 
  .[, .(RMSE = mean(sqrt((value - fcst_value)^2), na.rm = TRUE), 
        BIAS = mean(value - fcst_value, na.rm = TRUE)), 
    by = .(iop, exp, variable, lev, fcst_exp)] %>% 
  melt(measure.vars = c("RMSE", "BIAS"), variable.name = "estadistico", value.name = "value.est")

IOP <- tribble(
  ~iop, ~ini, ~end,
  "IOP07", ymd_hms("20181121150000"), ymd_hms("20181121210000"),
  "IOP08", ymd_hms("20181122140000"), ymd_hms("20181122200000")
) %>% setDT()

```

```{r}

sondeos %>% 
  .[, iop := fcase(launch_time %between% c(ymd_hms("20181121150000"), ymd_hms("20181121210000")), "IOP07",
                   launch_time %between% c(ymd_hms("20181122140000"), ymd_hms("20181122200000")), "IOP08")] %>% 
  .[variable %in% c("t", "td", "u", "v") & !str_detect(site, "/") & !is.na(fcst_value) & !is.na(iop)] %>% 
  .[, lev := cut_round(alt, seq(0, 20000, 1000))] %>% 
  .[, ":="(RMSE = mean(sqrt((value - fcst_value)^2), na.rm = TRUE), 
           BIAS = mean(value - fcst_value, na.rm = TRUE)), 
    by = .(iop, exp, variable, lev, fcst_exp)] %>% 
  melt(measure.vars = c("RMSE", "BIAS"), variable.name = "estadistico", value.name = "value.est") %>% 
  ggplot(aes(lev/1000, value.est)) +
  geom_hline(yintercept = 0, color = "grey30") +
  geom_line(aes(color = exp, linetype = estadistico)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp + iop~variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()
```

```{r rmse-sondeos-media}
extremos <- miembros %>% 
  .[, .(max_rmse = max(RMSE),
        min_rmse = min(RMSE)), by = .(exp, fcst_exp, lev, variable)]

media %>% 
  .[estadistico == "RMSE"] %>% 
  extremos[., on = .NATURAL] %>% 
  ggplot(aes(lev/1000, value.est)) +
  # geom_hline(yintercept = 0, color = "grey30") +
  geom_ribbon(aes(ymin = min_rmse, 
                  ymax = max_rmse, fill = exp), alpha = 0.2) +
  scale_fill_manual(guide = NULL, values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                                   E6 = "SATWND", E7 = "RAD")) +
  geom_line(aes(color = exp, linetype = estadistico)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp + iop~variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()

media %>% 
  .[estadistico == "RMSE"] %>% 
  miembros[., on = .NATURAL] %>% 
  ggplot(aes(lev/1000, value.est)) +
  # geom_hline(yintercept = 0, color = "grey30") +
  geom_line(alpha = 0.1, 
            aes(y = RMSE, color = exp, group = interaction(exp, mem))) +
  geom_line(aes(color = exp, linetype = estadistico)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp + iop~variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()
```


```{r rmse-sondeos-param}
pbl <- miembros[, .(RMSE = mean(RMSE)), by = .(exp, fcst_exp, pbl, lev, variable)]

media %>% 
  .[estadistico == "RMSE"] %>% 
  .[, c("exp", "variable", "lev", "fcst_exp", "RMSE" = "value.est")] %>% 
  .[, ":="(pbl = "Mean",
           RMSE = value.est)] %>% 
  .[, value.est := NULL] %>% 
  rbind(., pbl) %>% 
  ggplot(aes(lev/1000, RMSE)) +
  # geom_hline(yintercept = 0, color = "grey30") +
  geom_line(aes(y = RMSE, color = exp, linetype = pbl, group = interaction(exp, pbl))) +
  scale_linetype_manual(values = c(1, 2, 3, 4)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp ~ variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()


cum <- miembros[, .(RMSE = mean(RMSE)), by = .(exp, fcst_exp, cumulus, lev, variable)]

media %>% 
  .[estadistico == "RMSE"] %>% 
  .[, c("exp", "variable", "lev", "fcst_exp", "RMSE" = "value.est")] %>% 
  .[, ":="(cumulus = "Mean",
           RMSE = value.est)] %>% 
  .[, value.est := NULL] %>% 
  rbind(., cum) %>% 
  ggplot(aes(lev/1000, RMSE)) +
  # geom_hline(yintercept = 0, color = "grey30") +
  geom_line(aes(y = RMSE, color = exp, linetype = cumulus, group = interaction(exp, cumulus))) +
  scale_linetype_manual(values = c(4, 2, 3, 1)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp ~ variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()

```


```{r bias-sondeos-media}
extremos <- miembros %>% 
  .[, .(max_bias = max(BIAS),
        min_bias = min(BIAS)), by = .(exp, fcst_exp, lev, variable)]

media %>% 
  .[estadistico == "BIAS"] %>% 
  extremos[., on = .NATURAL] %>% 
  ggplot(aes(lev/1000, value.est)) +
  geom_hline(yintercept = 0, color = "grey30") +
  geom_ribbon(aes(ymin = min_bias, 
                  ymax = max_bias, fill = exp), alpha = 0.2) +
  geom_hline(yintercept = 0, color = "grey30") +
  scale_fill_manual(guide = NULL, values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                                   E6 = "SATWND", E7 = "RAD")) +
  geom_line(aes(color = exp, linetype = estadistico)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp + iop~variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()

media %>% 
  .[estadistico == "BIAS"] %>% 
  miembros[., on = .NATURAL] %>% 
  ggplot(aes(lev/1000, value.est)) +
  
  geom_line(alpha = 0.1, 
            aes(y = BIAS, color = exp, group = interaction(exp, mem))) +
  geom_line(aes(color = exp, linetype = estadistico)) +
  geom_hline(yintercept = 0, color = "grey30") +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp + iop~variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal() 
```


```{r bias-sondeos-param}
pbl <- miembros[, .(BIAS = mean(BIAS)), by = .(exp, fcst_exp, pbl, lev, variable)]

media %>% 
  .[estadistico == "BIAS"] %>% 
  .[, c("exp", "variable", "lev", "fcst_exp", "BIAS" = "value.est")] %>% 
  .[, ":="(pbl = "Mean",
           BIAS = value.est)] %>% 
  .[, value.est := NULL] %>% 
  rbind(., pbl) %>% 
  ggplot(aes(lev/1000, BIAS)) +
  geom_line(aes(y = BIAS, color = exp, linetype = pbl, group = interaction(exp, pbl))) +
  geom_hline(yintercept = 0, color = "grey30") +
  scale_linetype_manual(values = c(1, 2, 3, 4)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp ~ variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()


cum <- miembros[, .(BIAS = mean(BIAS)), by = .(exp, fcst_exp, cumulus, lev, variable)]

media %>% 
  .[estadistico == "BIAS"] %>% 
  .[, c("exp", "variable", "lev", "fcst_exp", "BIAS" = "value.est")] %>% 
  .[, ":="(cumulus = "Mean",
           BIAS = value.est)] %>% 
  .[, value.est := NULL] %>% 
  rbind(., cum) %>% 
  ggplot(aes(lev/1000, BIAS)) +
  geom_line(aes(y = BIAS, color = exp, linetype = cumulus, group = interaction(exp, cumulus))) +
  geom_hline(yintercept = 0, color = "grey30") +
  scale_linetype_manual(values = c(4, 2, 3, 1)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  coord_flip() +
  facet_grid(fcst_exp ~ variable, scales = "free_x", 
             labeller = labeller(variable = c("t" = "Temperature",
                                              "td" = "Dew point\ntemperature",
                                              "u" = "U wind",
                                              "v" = "V wind"))) +
  labs(y = NULL, x = "Height (Km)", color = NULL, linetype = NULL) +
  theme_minimal()

```


### Observaciones de superficie

```{r}
# files <- Sys.glob(paste0(derived_data, "/interp_obs/2018112200/interp*"))
# 
# obs <- purrr::map(files, function(f) {
#   print(f)
#   read_rds(f) %>%
#     .[, id := 1:.N, by = ens] %>%
#     .[, fcst_exp := "2018112200"] %>%
#     .[, exp := NULL] %>%
#     melt(measure.vars = c("E4", "E5", "E6", "E7"),
#          variable.name = "exp",
#          value.name = "fcst") %>%
#     .[, ":="(obs = if_else(usage.flag == 1, obs, NA_real_),
#              fcst = if_else(usage.flag == 1, fcst, NA_real_))] %>%
#     .[, c(list(obs = mean(obs, na.rm = TRUE),
#                fcst = mean(fcst, na.rm = TRUE)),
#           .SD[ens == 1]), by = .(id, exp), .SDcols = -c("obs", "fcst")] %>%
#     .[usage.flag == 1]
# 
# }) %>%
#   rbindlist()

obs_00 <- read_rds(paste0(derived_data, "/interp_obs/interp_obs_2018112200_mean.rds"))
obs_06 <- read_rds(paste0(derived_data, "/interp_obs/interp_obs_2018112206_mean.rds"))

media <- rbind(read_rds(paste0(derived_data, "/interp_obs/interp_obs_2018112200_mean2.rds")),
               read_rds(paste0(derived_data, "/interp_obs/interp_obs_2018112206_mean2.rds")))

miembros <- rbind(read_rds(paste0(derived_data, "/interp_obs/interp_obs_2018112200_mem.rds")),
                  read_rds(paste0(derived_data, "/interp_obs/interp_obs_2018112206_mem.rds")))


media %>% 
  melt(measure.vars = c("RMSE", "BIAS"), variable.name = "estadistico") %>% 
  .[estadistico == "RMSE"] %>% 
  ggplot(aes(date, value)) +
  geom_line(aes(color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "RMSE", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()

media %>% 
  melt(measure.vars = c("RMSE", "BIAS"), variable.name = "estadistico") %>% 
  .[estadistico == "BIAS"] %>% 
  ggplot(aes(date, value)) +
  geom_hline(yintercept = 0, color = "grey60") +
  geom_line(aes(color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "BIAS", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()
```

```{r}

extremos <- miembros %>% 
  .[, .(max_rmse = max(RMSE),
        min_rmse = min(RMSE)), by = .(var, exp, fcst_exp, date)]

media %>% 
  extremos[., on = .NATURAL] %>% 
  .[exp == "E7"] %>% 
  ggplot(aes(date, RMSE)) +
  geom_ribbon(aes(ymin = min_rmse, 
                  ymax = max_rmse, fill = exp, group = interaction(exp, fcst_exp)), alpha = 0.2) +
  scale_fill_manual(guide = NULL, values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                                   E6 = "SATWND", E7 = "RAD")) +
  geom_line(aes(color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "RMSE", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()


media %>% 
  .[, mem := "000"] %>% 
  rbind(., miembros) %>% 
  .[exp == "E7"] %>% 
  ggplot(aes(date, RMSE)) +
  geom_line(data = ~.x[mem != "000"], alpha = 0.1, 
            aes(y = RMSE, color = exp, linetype = fcst_exp, group = interaction(exp, mem, fcst_exp))) +
  geom_line(data = ~.x[mem == "000"], aes(color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "RMSE", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()

```


```{r}
copy(miembros) %>% 
  .[, mean_RMSE := mean(RMSE), by =  .(exp, fcst_exp, date, var)] %>% 
  ggplot(aes(date, RMSE)) +
  geom_line(aes(color = exp, linetype = fcst_exp, 
                grup = interaction(exp, fcst_exp, mem)), alpha = 0.1) +
  geom_line(aes(y = mean_RMSE, color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "RMSE", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()
```
```{r}

extremos <- miembros %>% 
  .[, .(max_bias = max(BIAS),
        min_bias = min(BIAS)), by = .(var, exp, fcst_exp, date)]

media %>% 
  extremos[., on = .NATURAL] %>% 
  .[exp == "E7"] %>% 
  ggplot(aes(date, BIAS)) +
  geom_ribbon(aes(ymin = min_bias, 
                  ymax = max_bias, fill = exp, group = interaction(exp, fcst_exp)), alpha = 0.2) +
  scale_fill_manual(guide = NULL, values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                                   E6 = "SATWND", E7 = "RAD")) +
  geom_line(aes(color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "BIAS", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()


media %>% 
  .[, mem := "000"] %>% 
  rbind(., miembros) %>% 
  .[exp == "E7"] %>% 
  ggplot(aes(date, BIAS)) +
  geom_line(data = ~.x[mem != "000"], alpha = 0.1, 
            aes(y = RMSE, color = exp, linetype = fcst_exp, group = interaction(exp, mem, fcst_exp))) +
  geom_line(data = ~.x[mem == "000"], aes(color = exp, linetype = fcst_exp)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  scale_date() +
  labs(subtitle = "BIAS", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_wrap(~ var, scales = "free_y") +
  theme_minimal()

```


```{r}
cum <- fisica[miembros, on = .NATURAL] %>% 
  separate(fisica, into = c("cumulus", "pbl")) %>% 
  .[, .(BIAS = mean(BIAS)), by = .(exp, fcst_exp, cumulus, var, date)]

media %>% 
  .[, c("exp", "var", "date", "fcst_exp", "BIAS")] %>% 
  .[, ":="(cumulus = "Mean")] %>% 
  rbind(., cum) %>% 
  ggplot(aes(date, BIAS)) +
  geom_line(aes(color = exp, linetype = cumulus)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  geom_hline(yintercept = 0, color = "grey30") +
  scale_linetype_manual(values = c(4, 2, 3, 1)) +
  scale_date() +
  labs(subtitle = "BIAS", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_grid(var~fcst_exp, scales = "free_y") +
  theme_minimal()

cum <- fisica[miembros, on = .NATURAL] %>% 
  separate(fisica, into = c("cumulus", "pbl")) %>% 
  .[, .(RMSE = mean(RMSE)), by = .(exp, fcst_exp, cumulus, var, date)]

media %>% 
  .[, c("exp", "var", "date", "fcst_exp", "RMSE")] %>% 
  .[, ":="(cumulus = "Mean")] %>% 
  rbind(., cum) %>% 
  ggplot(aes(date, RMSE)) +
  geom_line(aes(color = exp, linetype = cumulus)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  # geom_hline(yintercept = 0, color = "grey30") +
  scale_linetype_manual(values = c(4, 2, 3, 1)) +
  scale_date() +
  labs(subtitle = "RMSE", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_grid(var~fcst_exp, scales = "free_y") +
  theme_minimal()
```
```{r}
pbl <- fisica[miembros, on = .NATURAL] %>% 
  separate(fisica, into = c("cumulus", "pbl")) %>% 
  .[, .(BIAS = mean(BIAS)), by = .(exp, fcst_exp, pbl, var, date)]

media %>% 
  .[, c("exp", "var", "date", "fcst_exp", "BIAS")] %>% 
  .[, ":="(pbl = "Mean")] %>% 
  rbind(., pbl) %>% 
  ggplot(aes(date, BIAS)) +
  geom_line(aes(color = exp, linetype = pbl)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  geom_hline(yintercept = 0, color = "grey30") +
  scale_linetype_manual(values = c(1, 2, 3, 4)) +
  scale_date() +
  labs(subtitle = "BIAS", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_grid(var~fcst_exp, scales = "free_y") +
  theme_minimal()

pbl <- fisica[miembros, on = .NATURAL] %>% 
  separate(fisica, into = c("cumulus", "pbl")) %>% 
  .[, .(RMSE = mean(RMSE)), by = .(exp, fcst_exp, pbl, var, date)]

media %>% 
  .[, c("exp", "var", "date", "fcst_exp", "RMSE")] %>% 
  .[, ":="(pbl = "Mean")] %>% 
  rbind(., pbl) %>% 
  ggplot(aes(date, RMSE)) +
  geom_line(aes(color = exp, linetype = pbl)) +
  scale_color_manual(values = colores_exp, labels = c(E4 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E7 = "RAD")) +
  # geom_hline(yintercept = 0, color = "grey30") +
  scale_linetype_manual(values = c(1, 2, 3, 4)) +
  scale_date() +
  labs(subtitle = "RMSE", x = NULL, y = NULL, linetype = NULL, color = NULL) +
  facet_grid(var~fcst_exp, scales = "free_y") +
  theme_minimal()
```

### Precipitación

```{r}
files <- Sys.glob(paste0(derived_data, "/ppacum/E[4-7]_fcst_201811220*_mean_acum_30h.rds"))

pp_acum <- purrr::map(files, function(f) {
  
  meta <- unglue(basename(f), "{exp}_fcst_{fcst_init}_mean_acum_30h.rds")
  
  read_rds(f) %>% 
    .[, pp_acum := if_else(pp_acum < 0, 0, pp_acum)] %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             fcst_init = meta[[1]][["fcst_init"]])]
  
  
}) %>% rbindlist()

pp_acum %>% 
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = pp_acum, fill = stat(level_d)), 
                    proj = norargentina_lambert,
                    breaks = seq(20, 300, 20)) +
  scale_fill_viridis_c(guide = guide_colorsteps(barwidth = 20,
                                                barheight = 0.8), 
                       super = ScaleDiscretised,
                       limits = c(20, 300),
                       na.value = "white") +
  geom_point(data = square, aes(lon, lat), size = 0.1) +
  geom_mapa() +
  facet_grid(fcst_init ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  labs(fill = NULL) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  
  
  read_rds(paste0(derived_data, "ppacum/IMERG_30h.rds")) %>% 
  .[, run := "IMERG"] %>%
  .[,  c("lon", "lat") := wrf_project(x, y, inverse = TRUE, round = FALSE)] %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = pp_acum, fill = stat(level_d)), 
                    proj = norargentina_lambert,
                    breaks = seq(20, 300, 20)) +
  scale_fill_viridis_c(guide = guide_colorsteps(barwidth = 20,
                                                barheight = 0.8), 
                       super = ScaleDiscretised,
                       limits = c(20, 300),
                       na.value = "white") +
  geom_point(data = square, aes(lon, lat), size = 0.1) +
  geom_mapa() +
  facet_wrap(~run) +
  labs(fill = NULL) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  
  plot_layout(ncol = 2, widths = c(3, 1), guides = "collect") & theme(legend.position = 'bottom')


```

```{r}
files <- Sys.glob(paste0(derived_data, "/ppacum/E[4-7]_fcst_201811220*_prop_acum_30h.rds"))

pp_prop <- purrr::map(files, function(f) {
  
  meta <- unglue(basename(f), "{exp}_fcst_{fcst_init}_prop_acum_30h.rds")
  
  read_rds(f) %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             fcst_init = meta[[1]][["fcst_init"]])]
  
  
}) %>% rbindlist()

pp_prop %>% 
  .[umbral == 100] %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = prop*100, fill = stat(level_d)), 
                    proj = norargentina_lambert,
                    breaks = seq(10, 100, 10)) +
  scale_fill_gradientn(colours = rev(Redmonder::redmonder.pal(10, name = "qMSOStd")),
                       limits = c(10, 100),
                       guide = guide_colorsteps(barwidth = 20,
                                                barheight = 0.8),
                       super = ScaleDiscretised,
                       na.value = "white") +
  geom_point(data = square, aes(lon, lat), size = 0.1) +
  geom_mapa() +
  facet_grid(fcst_init ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  labs(fill = "100 mm") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  
  
  read_rds(paste0(derived_data, "ppacum/IMERG_30h.rds")) %>% 
  .[, run := "IMERG"] %>%
  .[,  c("lon", "lat") := wrf_project(x, y, inverse = TRUE, round = FALSE)] %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = pp_acum, fill = stat(level_d)), 
                    proj = norargentina_lambert,
                    breaks = seq(20, 300, 20)) +
  scale_fill_viridis_c(guide = guide_colorsteps(barwidth = 20,
                                                barheight = 0.8), 
                       super = ScaleDiscretised,
                       limits = c(20, 300),
                       na.value = "white") +
  geom_point(data = square, aes(lon, lat), size = 0.1) +
  geom_mapa() +
  facet_wrap(~run) +
  labs(fill = NULL) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  
  plot_layout(ncol = 2, widths = c(3, 1)) & theme(legend.position = 'bottom')


```


### Temperatura de brillo


```{r eval=FALSE, include=FALSE}

scale_color_topes <- function(colours = hex, 
                              limits = c(-90, 50), 
                              breaks = seq(-90, 50, 20),
                              guide = guide_colorbar(barheight = 15),
                              ...) {
  # https://github.com/garciafido/cima-goes/tree/master/src/cima/goes/img
  topes <- data.table::fread("../../temp_R/paleta_topes")
  colours <- rgb(topes$V2, topes$V3, topes$V4, maxColorValue = 255)
  
  scale_color_gradientn(colours = colours, 
                        limits = limits, 
                        breaks = breaks, 
                        guide = guide, ...) 
}

purrr::walk(c(0:30), function(h) {
  
  file_path <- paste0("~/datosmunin/EXP/E[4-7]/FCST/2018112200/CRTM/01/G16_20181122000000_", formatC(h, flag = "0", width = 3), "_00.nc")
  
  files <- Sys.glob(file_path)
  
  crtm <- purrr::map(files, function(f) {
    
    meta <- unglue(f, "/home/paola.corrales/datosmunin/EXP/{exp}/FCST/{fcst_exp}/CRTM/{mem}/G16_{fcst}_{hour}_{minutes}.nc")
    
    ReadNetCDF(f, vars = c(lat = "XLAT", lon = "XLONG", "CH10")) %>% 
      .[, CH10 := CH10 - 273.15] %>% 
      .[, ":="(exp = meta[[1]][["exp"]],
               mem = meta[[1]][["mem"]],
               fcst_exp = meta[[1]][["fcst_exp"]],
               date = ymd_hms(meta[[1]][["fcst"]]) + 
                 hours(as.numeric(meta[[1]][["hour"]])) +
                 minutes(as.numeric(meta[[1]][["minutes"]])))]
    
  }) %>% rbindlist()
  
  crtm %>% 
    ggplot(aes(lon, lat)) +
    geom_point(aes(color = CH10), size = 0.7) +
    # scale_color_viridis_c() +
    scale_color_topes(guide = guide_colorbar(barheight = 20)) +
    geom_mapa() +
    facet_wrap(~exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                 E6 = "SATWND", E7 = "RAD"))) +
    labs(caption = crtm[,date[1]]) +
    theme_minimal() +
    theme(panel.ontop = TRUE,
          panel.grid = element_line(linetype = 3)) 
  
  ggsave(paste0("CH10_2018112200_", format(crtm[,date[1]], "%Y%m%d%H%M"), ".png"))
  
})
```

### Campos de variables

```{r}
df <- data.frame(
  lead_time = rep(c(6, 12, 18), 4),
  exp = rep(c("E4", "E5", "E6", "E7"), each = 3)
)

files <- purrr::map2_chr(df$lead_time, df$exp, function(l, e) {
  paste0("/home/paola.corrales/datosmunin/EXP/", e, "/FCST/2018112200/NPP/NPP_2018-11-22_00_FC", 
         formatC(l, width = 2, flag = "0"), ".nc")
})

coord <- ReadNetCDF(files[1], vars = c("XLAT", "XLONG"))

var_00 <- purrr::map(files, function(f) {
  
  meta <- unglue(f, "/home/paola.corrales/datosmunin/EXP/{exp}/FCST/{fcst_exp}/NPP/NPP_{x}_FC{lead}.nc")
  
  ReadNetCDF(f, vars = c("Q", "T", "V"), subset = list(lev = c(800, 1000))) %>% 
    .[, .(Q = mean(Q),
          T = mean(T),
          V = mean(V)), by = .(lat, lon)] %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             fcst_exp = meta[[1]][["fcst_exp"]],
             lead_date = ymd_h(meta[[1]][["fcst_exp"]]) + hours(as.numeric(meta[[1]][["lead"]])))]
  
}) %>% rbindlist()

mcape_00 <- purrr::map(files, function(f) {
  
  meta <- unglue(f, "/home/paola.corrales/datosmunin/EXP/{exp}/FCST/{fcst_exp}/NPP/NPP_{x}_FC{lead}.nc")
  
  ReadNetCDF(f, vars = c("MCAPE", "MDBZ")) %>% 
    .[, .(MCAPE = mean(MCAPE, na.rm = TRUE),
          MDBZ = mean(MDBZ, na.rm = TRUE)), by = .(lat, lon)] %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             fcst_exp = meta[[1]][["fcst_exp"]],
             lead_date = ymd_h(meta[[1]][["fcst_exp"]]) + hours(as.numeric(meta[[1]][["lead"]])))]
  
}) %>% rbindlist()
```

```{r}
df <- data.frame(
  lead_time = rep(c(0, 6, 12), 4),
  exp = rep(c("E4", "E5", "E6", "E7"), each = 3)
)

files <- purrr::map2_chr(df$lead_time, df$exp, function(l, e) {
  paste0("/home/paola.corrales/datosmunin/EXP/", e, "/FCST/2018112206/NPP/NPP_2018-11-22_06_FC", 
         formatC(l, width = 2, flag = "0"), ".nc")
})

coord <- ReadNetCDF(files[1], vars = c("XLAT", "XLONG"))

var_06 <- purrr::map(files, function(f) {
  
  meta <- unglue(f, "/home/paola.corrales/datosmunin/EXP/{exp}/FCST/{fcst_exp}/NPP/NPP_{x}_FC{lead}.nc")
  
  ReadNetCDF(f, vars = c("Q", "T", "V"), subset = list(lev = c(800, 1000))) %>% 
    .[, .(Q = mean(Q),
          T = mean(T),
          V = mean(V)), by = .(lat, lon)] %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             fcst_exp = meta[[1]][["fcst_exp"]],
             lead_date = ymd_h(meta[[1]][["fcst_exp"]]) + hours(as.numeric(meta[[1]][["lead"]])))]
  
}) %>% rbindlist()

mcape_06 <- purrr::map(files, function(f) {
  
  meta <- unglue(f, "/home/paola.corrales/datosmunin/EXP/{exp}/FCST/{fcst_exp}/NPP/NPP_{x}_FC{lead}.nc")
  
  ReadNetCDF(f, vars = c("MCAPE", "MDBZ")) %>% 
    .[, .(MCAPE = mean(MCAPE, na.rm = TRUE),
          MDBZ = mean(MDBZ, na.rm = TRUE)), by = .(lat, lon)] %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             fcst_exp = meta[[1]][["fcst_exp"]],
             lead_date = ymd_h(meta[[1]][["fcst_exp"]]) + hours(as.numeric(meta[[1]][["lead"]])))]
  
}) %>% rbindlist()
```



```{r}
var_00 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>% 
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = Q, fill = stat(level_d)), proj = norargentina_lambert,
                    breaks = seq(0, 20, 2)) +
  scale_fill_distiller(name = NULL, super = ScaleDiscretised,
                       palette = "BrBG", direction = 1,
                       limits = c(1, 20),
                       guide = guide_colorsteps(#inside = FALSE,
                         barwidth = 25,
                         barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

var_06 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>% 
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = Q, fill = stat(level_d)), proj = norargentina_lambert,
                    breaks = seq(0, 20, 2)) +
  scale_fill_distiller(name = NULL, super = ScaleDiscretised,
                       palette = "BrBG", direction = 1,
                       limits = c(1, 20),
                       guide = guide_colorsteps(#inside = FALSE,
                         barwidth = 25,
                         barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))
```
```{r}
var_00 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = V, fill = stat(level_d)), proj = norargentina_lambert) +
  scale_fill_divergent_discretised(name = NULL,
                                   guide = guide_colorsteps(#inside = FALSE,
                                     barwidth = 25,
                                     barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

var_06 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = V, fill = stat(level_d)), proj = norargentina_lambert) +
  scale_fill_divergent_discretised(name = NULL,
                                   guide = guide_colorsteps(#inside = FALSE,
                                     barwidth = 25,
                                     barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))


```

```{r}
var_00 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = T - 273.15, fill = stat(level_d)), proj = norargentina_lambert,
                    breaks = seq(0, 40, 5)) +
  scale_fill_distiller(name = NULL, super = ScaleDiscretised,
                       palette = "OrRd", direction = 1,
                       limits = c(1, 40),
                       guide = guide_colorsteps(#inside = FALSE,
                         barwidth = 25,
                         barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

var_06 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = T - 273.15, fill = stat(level_d)), proj = norargentina_lambert,
                    breaks = seq(0, 40, 5)) +
  scale_fill_distiller(name = NULL, super = ScaleDiscretised,
                       palette = "OrRd", direction = 1,
                       limits = c(1, 40),
                       guide = guide_colorsteps(#inside = FALSE,
                         barwidth = 25,
                         barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))
```
```{r}
mcape_00 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  # geom_point(aes(color = MCAPE)) +
  geom_contour_fill(aes(z = MCAPE, fill = stat(level_d)), proj = norargentina_lambert,
                    breaks = seq(0, 4500, 500)) +
  scale_fill_distiller(name = NULL, super = ScaleDiscretised,
                       palette = "YlOrRd", direction = 1,
                       guide = guide_colorsteps(#inside = FALSE,
                         barwidth = 25,
                         barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

mcape_06 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  # geom_point(aes(color = MCAPE)) +
  geom_contour_fill(aes(z = MCAPE, fill = stat(level_d)), proj = norargentina_lambert,
                    breaks = seq(0, 4500, 500)) +
  scale_fill_distiller(name = NULL, super = ScaleDiscretised,
                       palette = "YlOrRd", direction = 1,
                       guide = guide_colorsteps(#inside = FALSE,
                         barwidth = 25,
                         barheight = 0.8)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))
```
```{r}
values <- c(-19.5, -12, -7.5, -3, 1.5, 6, 9, 12, 15, 16.5, 18, 19.5, 21, 
22.5, 24, 25.5, 27, 28.5, 30, 31.5, 33, 34.5, 36, 37.5, 39, 40.5, 
42, 43.5, 45, 46.5, 48, 49.5, 51, 52.5, 54, 55.5, 57, 58.5, 60, 
61.5, 63, 64.5, 66, 69, 76.5)

colours <- c("#3D4170", "#3D4E7C", "#3B5B84", "#3A6695", "#3672A4", "#3188BD", 
"#2F89B9", "#2896C7", "#24A4CF", "#2AB1D6", "#53F336", "#4BE231", 
"#44D12F", "#3FC12B", "#3AAF25", "#32A11F", "#2C881E", "#227216", 
"#EEEF39", "#DEE539", "#D7DA35", "#CED130", "#C4C52B", "#CBAE1F", 
"#D59716", "#DB8116", "#EC0A2E", "#CB001A", "#C20013", "#B10009", 
"#990000", "#C3005D", "#D600A2", "#E901E9", "#CC00CC", "#B100B5", 
"#9800A0", "#FEFFFF", "#DFF5EC", "#C5F1E0", "#B7ECD8", "#A6ECCF", 
"#95E3C5", "#85E0BD")

mcape_00 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  # geom_point(aes(color = MCAPE)) +
  geom_contour_fill(aes(z = MDBZ, fill = stat(level)), 
                    proj = norargentina_lambert,
                    breaks = values) +
  scale_fill_manual(values = colours, 
                    drop = FALSE, guide = guide_colorsteps(barwidth = 0.8, 
                                                                         barheight = 30)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))

mcape_06 %>% 
  coord[., on = .NATURAL] %>% 
  .[, c("x", "y") := wrf_project(XLONG, XLAT)] %>% 
  .[, lead_date := factor(lead_date)] %>%
  
  ggplot(aes(x, y)) +
  # geom_point(aes(color = MCAPE)) +
  geom_contour_fill(aes(z = MDBZ, fill = stat(level)), 
                    proj = norargentina_lambert,
                    breaks = values) +
  scale_fill_manual(values = colours, 
                    drop = FALSE, guide = guide_colorsteps(barwidth = 0.8, 
                                                                         barheight = 30)) +
  geom_mapa() +
  cordillera +
  facet_grid(lead_date ~ exp, labeller = labeller(exp = c(E4 = "CONV", E5 = "AUT", 
                                                          E6 = "SATWND", E7 = "RAD"))) +
  theme_minimal() +
  theme(panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3))
```

