---
title: "Poster"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mesoda)
library(metR)
library(tidyverse)
library(lubridate)
library(data.table)
library(here)
library(patchwork)
library(unglue)
library(knitr)
library(kableExtra)

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")


geom_mapa <- function() {
  list(geom_sf(data = map, fill = NA, color = "black", size = 0.2, inherit.aes = FALSE),
       coord_sf(xlim = c(-76, -52), ylim = c(-41, -20)))
}

sensores <- c("amsua_n15",
              "amsua_n18",
              "amsua_n19",
              "amsua_metop-b",
              "amsua_aqua",
              "airs_aqua",
              "iasi_metop-a",
              "iasi_metop-b", 
              "hirs4_n19",
              "hirs4_metop-a",
              "hirs4_metop-b",
              "mhs_metop-a",
              "mhs_metop-b",
              "mhs_n18",
              "mhs_n19",
              "mhs_metop-a",
              "atms_npp",
              "atms_n20",
              "cris-fsr_npp",
              "cris-fsr_n20"
)

multiespectrales <- c("airs_aqua",
                      "iasi_metop-a",
                      "iasi_metop-b")
```

## Coeficientes


```{r}
files <- c(Sys.glob("/home/paola.corrales/datosmunin3/EXP/prueba_BC/ANA/*/satbias_enkf/satbias_2*"),
           Sys.glob("/home/paola.corrales/datosmunin3/EXP/E8/ANA/*/satbias_enkf/satbias_2*"))

satbias <- map(files, function(f){
  
  meta <- unglue(f, "/home/paola.corrales/datosmunin3/EXP/{periodo}/ANA/{date_ana}/satbias_enkf/satbias_{date}")
 
  read_satbias(f) %>% 
    as.data.table() %>% 
    .[, ":="(date = ymd_hms(meta[[1]][["date"]]),
             periodo = meta[[1]][["periodo"]])] 
  
}) %>% 
  rbindlist()

satbias <- satbias[sensor %in% sensores]

satinfo <- fread(here("analysis", "data", "derived_data", "satinfo.txt")) %>% 
  setnames(c("!sensor/instr/sat", "chan"), c("sensor", "channel"))

satbias <- satinfo[satbias, on = c("sensor", "channel")]

```


```{r coef-amsua-n15, fig.cap="Coeficientes de corrección de bias en cada ciclo de asimilación para los canales 5 a 9 del sensor AMSU-A de NOAA-15."}

periodos <- tibble(periodo = c("prueba_Bc", "E8"),
                   start = ymd_hms(c(20181111180000, 20181120180000)),
                   end = ymd_hms(c(20181118050000, 20181123120000)))

this_sensor <- sensores[1]

satbias[sensor == this_sensor & iuse == 1] %>% 
  .[channel %in% c(4:9)] %>%
  melt(measure.vars = paste0("coeff", c(1, 3:5, 8))) %>% 
  ggplot(aes(date, value)) +
  geom_path(aes(color = variable, group = interaction(variable, periodo)), size= 0.5) +
  geom_rect(data = periodos, aes(xmin = start, xmax = end, fill = periodo),
                ymin = -Inf, ymax = Inf, alpha = 0.1, inherit.aes = FALSE) +
  scale_color_brewer(type = "qual", palette = "Dark2",
                     labels = c("coeff1" = "Offset",
                                "coeff3" = "CLW",
                                "coeff4" = "TLR^2",
                                "coeff5" = "TLR",
                                "coeff8" = "Emissivity")) +
  scale_fill_manual(values = c("grey70", "black"), labels = c("prueba_Bc" = "training", "E8" = "RAD")) +
  # scale_linetype_discrete(name = "", labels = c("pre-RAD1", "pre-RAD2")) +
  scale_x_datetime(date_labels = "%d") +
  labs(color = NULL, x = "Date", y = NULL, fill = NULL) +
  facet_wrap(~channel, scales = "free_y", ncol = 3, labeller = labeller(channel = c("4" = "Channel 4",
                                                                                    "5" = "Channel 5",
                                                                                    "6" = "Channel 6",
                                                                                    "7" = "Channel 7",
                                                                                    "8" = "Channel 8",
                                                                                    "9" = "Channel 9"))) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
files <- Sys.glob("~/datosmunin3/EXP/E8/ANA/2018112*/diagfiles/asim*.ensmean")

files <- files[str_detect(files, "conv", negate = TRUE)]

rad <- read_diag_rad(files, "E8") %>% 
  satinfo[., on = c("sensor", "channel")] %>% 
  .[,  type :=  fifelse(sensor %in% multiespectrales, "multiespectral", "otro")] %>% 
  separate(sensor, into = c("sensor", "plat"), sep = "_")


rad[errinv %between% c(0.0000316227, 1000) & 
      qc == 0 & 
      iuse == 1 &
      peakwt %between% c(0.001, 1200), 
    .(tbc_mean = mean(tbc),
      tbcnob_mean = mean(tbcnob)), by = .(sensor, channel, date)] %>% 
  # .[, diff := abs(tbcnob_mean) - abs(tbc_mean)] %>% 
  # .[, range(diff, na.rm = TRUE)]
  melt(id.vars = c("sensor", "channel", "date")) %>% 
  ggplot(aes(value)) +
  geom_histogram(aes(fill = variable, y = stat(density)), binwidth = 0.1,
                 alpha= 0.3, position = "identity") +
  geom_density(aes(color = variable, y = stat(density))) +
  geom_rug(data = ~.x[variable == "diff"]) +
  # scale_fill_manual(values = c("darkorange", "purple", "cyan4")) +
  scale_fill_viridis_d(labels = c("OmB bc", "OmB nobc", "Difference")) +
  scale_color_viridis_d(labels = c("OmB bc", "OmB nobc", "Difference")) +
  geom_vline(xintercept = 0, color = "grey40") +
  coord_cartesian(xlim = c(-2.5, 2.5)) +
  facet_wrap(~sensor, labeller = labeller(sensor = toupper)) +
  labs(fill = NULL, x = NULL, color = NULL) +
  theme_minimal() +
  theme(legend.position = "bottom")

rad[errinv %between% c(0.0000316227, 1000) & 
      qc == 0 & 
      iuse == 1 &
      peakwt %between% c(0.001, 1200) &
      sensor == "amsua" &
      plat == "n15", 
    .(tbc_mean = mean(tbc),
      tbcnob_mean = mean(tbcnob),
      .N), by = .(sensor, channel, date)] %>% 
   melt(id.vars = c("sensor", "channel", "date")) %>% 
  .[channel %in% c(4:9)] %>% 
  ggplot(aes(value)) +
  geom_histogram(aes(fill = variable, y = stat(density)), binwidth = 0.1,
                 alpha= 0.3, position = "identity") +
  geom_density(aes(color = variable, y = stat(density))) +
  geom_rug(data = ~.x[variable == "diff"]) +
  # scale_fill_manual(values = c("darkorange", "purple", "cyan4")) +
  scale_fill_viridis_d(labels = c("OmB bc", "OmB nobc", "Difference")) +
  scale_color_viridis_d(labels = c("OmB bc", "OmB nobc", "Difference")) +
  geom_vline(xintercept = 0, color = "grey40") +
  coord_cartesian(xlim = c(-2.5, 2.5)) +
  facet_wrap(~channel, labeller = labeller(sensor = toupper)) +
  labs(fill = NULL, x = NULL, color = NULL) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
rad[errinv %between% c(0.0000316227, 1000) & 
      qc == 0 & 
      iuse == 1 &
      peakwt %between% c(0.001, 1200)] %>% 
  .[, lev := factor(cut_round(peakwt, breaks = seq(0, 1050, 50)))] %>% 
  .[, .(omb = mean(tbc),
        n = .N), by = .(date, lev, exp)] %>% 
  .[lev != 1025] %>% 
  ggplot(aes(date, fct_rev(lev))) +
  geom_tile(aes(fill = n)) +
  scale_fill_viridis_c(trans = scales::log10_trans(), breaks = c(1, 10, 100, 1000, 10000),
                       guide = guide_colourbar(barheight = 8,
                                               barwidth = 0.5)) +
  
  scale_date() +
  labs(x = NULL, fill = NULL, y = "pressure (hPa)") +
  theme_minimal() +
  theme(aspect.ratio = 1/1.5) 
```
```{r fss, fig.cap="FSS calculated over a 6-hours moving window for different thresholds and scales."}
files <- Sys.glob("/home/paola.corrales/mesoda/analysis/data/derived_data/fss_6h_ana_ens_E[2-8].csv")

fss <- purrr::map(files, function(f) {
  
  fread(f) %>% 
    .[, date := as_datetime(date)]
}) %>% 
  rbindlist()

colores_exp <- c(E2 = "#0077BB", E5 = "#88CCEE", E6 = "#EE7733", E8 = "#CC3311") 

fss %>% 
  .[w %in% c(1, 11) & q %in% c(1, 25) & exp %in% c("E2", "E5", "E6", "E8")] %>% 
  # .[date %between% c(ymd_hms(20181122000000), ymd_hms(20181123120000))] %>% 
  ggplot(aes(date, fss)) +
  geom_hline(yintercept = 1, color = "darkgray") +
  geom_line(aes(color = exp)) +
  # geom_point(aes(color = exp)) +
  scale_color_manual(values = colores_exp, labels = c(E2 = "CONV", E5 = "AUT", 
                                                      E6 = "SATWND", E8 = "RAD")) +
  scale_date(20181122000000, 20181123000000, "12 hours") +
  coord_cartesian(xlim = c(ymd_hms(20181122000000), ymd_hms(20181123120000))) +
  facet_grid(w~q, labeller = labeller(q = c("1" = "1 mm", "5" = "5 mm", 
                                            "10" = "10 mm", "25" = "25 mm"),
                                      w = c("1" = "10 km", "5" = "50 km", "11" = "100 km", 
                                            "51" = "500 km", "101" = "1000 km"))) +
  labs(color = NULL, x = NULL, y = "FSS") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r dbz-mean, fig.cap="Observed maximum reflectivity in the column (upper row) and ensemble mean maximum reflectivity for CONV and RAD at different times (bottom two rows).", include=FALSE}
proj_radar <- "+proj=tmerc +lon_0=-61.5 +lat_0=-32 +k_0=1 +ellps=WGS84"

rad_loc <- read_csv(here("analysis", "data", "derived_data", "radar_loc.csv"))

files <- Sys.glob("/home/jruiz/datosmunin3/datos/DATOS_RADAR/MOSAICO/*.nc")[c(1, 7)]
# Solo un par de horarios 10, 13, 16 y 19 UTC

dbz_obs <- purrr::map(files, function(f) {
  
  
  ReadNetCDF(f, vars = "DBZH_cor") %>%
    .[!is.na(DBZH_cor)] %>% 
    .[, .(DBZH_cor = max(DBZH_cor, na.rm = TRUE)), by = .(x, y)] %>% 
    .[, max_dbz := 10 * log10(DBZH_cor)] %>% 
    .[, ":="(date = ymd_hms(str_remove(basename(f), ".nc")),
             DBZH_cor = NULL)] %>% 
    .[, c("lon", "lat") := proj4::project(list(x, y), proj_radar, inverse = TRUE)]
  
}) %>% rbindlist() %>% 
  .[, run := "OBSERVATIONS"]

dates <- c("20181122100000", 
           "20181122160000")
files <- Sys.glob(paste0(derived_data, "dbz/maxdbz_ana_E[28]_", dates, ".nc"))

dbz_ana <- purrr::map(files, function(f){
  
  meta <- unglue(basename(f), "maxdbz_ana_{exp}_{date}.nc")
  ReadNetCDF(f, vars = c(lon = "XLONG", lat = "XLAT", "max_dbz")) %>% 
    .[, ":="(exp = meta[[1]][["exp"]],
             date = ymd_hms(meta[[1]][["date"]]))] %>% 
    .[, c("x", "y") := wrf_project(lon, lat)] 
}) %>% 
  rbindlist()  %>% 
  .[, run := fifelse(exp == "E8", "RAD", "CONV")]

values <- c(-19.5, -12, -7.5, -3, 1.5, 6, 9, 12, 15, 16.5, 18, 19.5, 21, 
            22.5, 24, 25.5, 27, 28.5, 30, 31.5, 33, 34.5, 36, 37.5, 39, 40.5, 
            42, 43.5, 45, 46.5, 48, 49.5, 51, 52.5, 54, 55.5, 57, 58.5, 60, 
            61.5, 63, 64.5, 66, 69, 76.5)

colours <- c("#3D4170", "#3D4E7C", "#3B5B84", "#3A6695", "#3672A4", "#3188BD", 
             "#2F89B9", "#2896C7", "#24A4CF", "#2AB1D6", "#53F336", "#4BE231", 
             "#44D12F", "#3FC12B", "#3AAF25", "#32A11F", "#2C881E", "#227216", 
             "#EEEF39", "#DEE539", "#D7DA35", "#CED130", "#C4C52B", "#CBAE1F", 
             "#D59716", "#DB8116", "#EC0A2E", "#CB001A", "#C20013", "#B10009", 
             "#990000", "#C3005D", "#D600A2", "#E901E9", "#CC00CC", "#B100B5", 
             "#9800A0", "#FEFFFF", "#DFF5EC", "#C5F1E0", "#B7ECD8", "#A6ECCF", 
             "#95E3C5", "#85E0BD")


dbz_obs %>% 
  # .[date == unique(date)[1]] %>% 
  .[, date := factor(date)] %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = max_dbz, fill = stat(level)), 
                    proj = proj_radar,
                    breaks = values) +
  scale_fill_manual(values = colours, 
                    labels = function(x) JumpBy(x, 3, fill = ""),
                    drop = FALSE, 
                    guide = guide_colorsteps(barwidth = 20, 
                                             barheight = 0.5)) +
  # geom_point(data = rad_loc, aes(lon, lat, color = factor(nradar)), size = 2) +
  geom_path(data = rad_loc, aes(lon, lat, group = ID), size = 0.4) +
  geom_mapa() +
  facet_grid(run ~ date) +
  labs(x = NULL, y = NULL, fill = "COLMAX (dBZ)") +
  theme_minimal() +
  theme(legend.position = "bottom",
        # legend.box.spacing = margin(0, 0, 0, 0),
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3)) +
  
  dbz_ana %>% 
  .[, date := factor(date)] %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = max_dbz, fill = stat(level)), 
                    proj = norargentina_lambert,
                    breaks = values) +
  scale_fill_manual(values = colours, 
                    labels = function(x) JumpBy(x, 3, fill = ""),
                    drop = FALSE, 
                    guide = guide_colorsteps(barwidth = 20, 
                                             barheight = 0.5)) +
  # geom_point(data = rad_loc, aes(lon, lat, color = factor(nradar)), size = 2) +
  geom_path(data = rad_loc, aes(lon, lat, group = ID), size = 0.4) +
  geom_mapa() +
  facet_grid(run ~ date) +
  labs(x = NULL, y = NULL, fill = "COLMAX (dBZ)") +
  theme_minimal() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        panel.ontop = TRUE,
        panel.grid = element_line(linetype = 3)) +
  
  plot_layout(ncol = 1, heights = c(1, 2), guides = "collect") & 
  theme(legend.position = 'bottom')

```
```{r}
oficiales <- fread(here("analysis", "data", "raw_data", "E2_asim_conv_20181121120000.ensmean"), 
                   na.strings = c("0.100E+11", "-0.100E+06", "-99999.90", "-100000.00")) %>% 
  .[, c("V2", "V4") := NULL] %>% 
  setnames(colnames(.), c("var", "stationID", "type", "dhr", "lat", "lon", "pressure", "usage.flag", "flag", "obs", "obs.guess", "obs2", "obs.guess2", "rerr")) %>% 
  .[type %in% c(181, 281)] %>% unique(by = c("stationID")) %>%
  .[!str_detect(stationID, pattern = "[A-Z]")] %>% 
  .[, source := "Sfc - Official"]

no_oficiales <- fread(here("analysis", "data", "raw_data", "E5_asim_conv_20181121120000.ensmean"), 
                      na.strings = c("0.100E+11", "-0.100E+06", "-99999.90", "-100000.00")) %>% 
  .[, c("V2", "V4") := NULL] %>% 
  setnames(colnames(.), c("var", "stationID", "type", "dhr", "lat", "lon", "pressure", "usage.flag", "flag", "obs", "obs.guess", "obs2", "obs.guess2", "rerr")) %>% 
  .[type %in% c(181, 187)] %>% 
  .[!str_detect(stationID, "SMN")] %>%
  .[!(stationID %in% oficiales$stationID)] %>% 
  unique(by = c("stationID")) %>% 
  .[, source := "Sfc - Non-official"]

obs <- rbind(no_oficiales, oficiales)

lista_sondeos <- fread(here("analysis/data/derived_data/lista_sondeos.csv")) %>% 
  .[, periodo := fcase(nominal_launch_time %between% c(ymd_hms("20181121150000"), ymd_hms("20181121210000")),  "IOP07", 
                       nominal_launch_time %between% c(ymd_hms("20181122140000"), ymd_hms("20181122200000")),  "IOP08", 
                       default = "Others")
  ]

dominio <- fread(here("analysis", "data", "derived_data", "dominio_hgt.csv")) %>% 
  .[, c("x", "y") := wrf_project(lon, lat)]

dominio %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = hgt), proj = norargentina_lambert,
                    breaks = seq(0, 6000, 500)) +
  scale_fill_gradient(low = "#f2f2f2", high = "#333333",
                      name = NULL,
                      breaks = seq(0, 6000, 1000),
                      guide = guide_colorstrip(barwidth = 15,
                                               barheight = 0.5)) +
  geom_mapa() +
  geom_point(data = obs, aes(ConvertLongitude(lon), lat, 
                             color = source, shape = source), 
             size = 1, alpha = 0.8) + 
  scale_shape_manual(name = NULL,  
                     breaks = c("Sfc - Non-official", "Sfc - Official"),
                     labels = c("ASWS","CSWS"), values = c(15, 17),
                     guide = guide_legend(override.aes = list(size = 2))) +
  scale_color_manual(name =  NULL, 
                     values = c("Sfc - Non-official" = "#00695c", 
                                "Sfc - Official" = "#FD8002"),
                     breaks = c("Sfc - Non-official", "Sfc - Official"),
                     labels = c("ASWS","CSWS"),
                     guide = guide_legend(override.aes = list(size = 2))) +
  geom_point(data = square, aes(lon, lat), size = 0.2) +
  # geom_point(data = square2, aes(lon, lat), size = 0.2, color = "#CC3311") +
  theme_minimal(base_size = 9) +
  theme(legend.position = "bottom", 
        legend.box = "vertical") 
  # ,
```

